name: Extract from Docker

on: push

jobs:
  web-vault:
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release zip

      - name: Install Docker
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io

      - name: Get Tag name
        id: tag-name
        uses: battila7/get-version-action@v2

      - name: Extract web-vault
        run: |
          docker create --name vw vaultwarden/server:${{ steps.tag-name.outputs.version }}
          docker cp vw:/web-vault ./
          docker rm vw
          zip -r web-vault web-vault

      - name: Upload web-vault
        uses: actions/upload-artifact@v1
        with:
          path: web-vault.zip
          name: web-vault.zip

  vaultwarden-armv7:
    runs-on: ubuntu-22.04

    steps:
      - name: Get Tag name
        id: tag-name
        uses: battila7/get-version-action@v2

      - name: Fetch code
        uses: actions/checkout@master
        with:
          repository: dani-garcia/vaultwarden
          ref: refs/tags/${{ steps.tag-name.outputs.version }}
          path: vaultwarden

      - name: Install dependencies
        run: |
          sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release zip

      - name: Install Docker
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io

      - name: Build and extract vaultwarden
        run: |
          cd vaultwarden
          docker build --build-arg DB=postgresql -t vaultwarden-build -f docker/armv7/Dockerfile .
          docker create --name vw vaultwarden-build
          docker cp vw:/vaultwarden ./
          docker rm vw

      - name: Upload vaultwarden
        uses: actions/upload-artifact@v1
        with:
          path: vaultwarden
          name: vaultwarden_armv7

  libssl1_1-armv7:
    runs-on: ubuntu-22.04

    steps:
      - name: Install Docker
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io

      - name: Fetch image and extract libraries
        run: |
          docker create --name vw --platform=linux/arm/v7 vaultwarden/server:1.26.0
          docker cp vw:/usr/lib/arm-linux-gnueabihf/libssl.so.1.1 .
          docker cp vw:/usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1 .
          docker rm vw

      - name: Upload libssl
        uses: actions/upload-artifact@v3
        with:
          path: ./*.so.1.1
          name: libssl1.1

  release:
    runs-on: ubuntu-22.04
    needs: [web-vault, vaultwarden-armv7, libssl1_1-armv7]

    steps:
    - name: Download vaultwarden_armv7 binary
      uses: actions/download-artifact@v1
      with:
        name: vaultwarden_armv7

    - name: Download web-vault
      uses: actions/download-artifact@v1
      with:
        name: web-vault.zip

    - name: Download libssl
      uses: actions/download-artifact@v1
      with:
        name: libssl1.1

    - name: List files
      run:
        ls -la vaultwarden_armv7/vaultwarden
        ls -la web-vault.zip
        ls -la libssl1.1

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          vaultwarden_armv7/vaultwarden
          web-vault.zip
          libssl1.1/libcrypto.so.1.1
          libssl1.1/libssl.so.1.1
